image: node:13.6.0

variables:
  PUBLIC_URL: "/asha-health"
  DAST_WEBSITE: https://illemonati.gitlab.io/asha-health

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml





pages:
  stage: deploy
  script:
    - yarn
    - yarn build
    - rm -rf public
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
